---

- name: tinc | check if tinc_hostname is defined
  assert:
    that: tinc_hostname is defined and tinc_hostname|length > 0

- name: tinc | check if tinc_rsa_key is defined
  assert:
    that: tinc_rsa_key is defined and tinc_rsa_key|length > 0

- name: tinc | check tinc_vpn is defined
  assert:
    that: tinc_vpn is defined and tinc_vpn|length > 0

- name: tinc | check tinc_vpn list if vpn is defined
  assert:
    that:
      - item.vpn is defined and item.vpn|length > 0
  with_items: "{{tinc_vpn}}"

- name: tinc | check tinc_vpn list if name is defined
  assert:
    that:
      - item.name is defined and item.name|length > 0
  with_items: "{{tinc_vpn}}"

- name: tinc | check tinc_vpn list if name is unique
  assert:
    that:
      - tinc_vpn|map(attribute='name')|list|length == tinc_vpn|map(attribute='name')|list|unique|length

- name: tinc | check tinc_vpn list if address is defined and well formed
  assert:
    that:
      - item.address is defined and item.address|length > 0
      - item.address | ipaddr
      - item.address | ipaddr('address')
  with_items: "{{tinc_vpn}}"

- name: tinc | check tinc_vpn list if subnet is well formed if defined
  assert:
    that:
      - item.subnet is not defined or item.subnet|length > 0
      - item.subnet is not defined or item.subnet | ipaddr
      - item.subnet is not defined or item.subnet.split('/')[1] | int
  with_items: "{{tinc_vpn}}"

- name: tinc | check tinc_vpn list if vpn_address is defined and well formed
  assert:
    that:
      - item.vpn_address is defined and item.vpn_address|length > 0
      - item.vpn_address | ipaddr
      - item.vpn_address | ipaddr('address')
  with_items: "{{tinc_vpn}}"

- name: tinc | check tinc_vpn list if vpn_prefixlength is defined and well formed
  assert:
    that:
      - item.vpn_prefixlength is defined
      - item.vpn_prefixlength | int
      - item.vpn_prefixlength >= 0 and item.vpn_prefixlength <= 32
  with_items: "{{tinc_vpn}}"

- name: tinc | check tinc_vpn list if public_key is defined
  assert:
    that:
      - item.public_key is defined and item.public_key|length > 0
  with_items: "{{tinc_vpn}}"

- name: tinc | check if tinc_hostname in tinc_vpn
  assert:
    that: tinc_hostname in (tinc_vpn|map(attribute='name')|list)
